### ISSUE TITLE
How do I use this with bungeecoord?

### ISSUE THREAD

**Issue by marcangeloh** [LagBug/XProtect#1]
Hey LagBug, great job on the plugin. I was wondering if it offered bungee/waterfall support? And if so how do I install it (Just server files or also proxy)?

**Comment by JovannMC** [comment]
Hey, for support LagBug likes you to join the discord server (lagbug.me/discord). But BungeeCord/Waterfall support is, I believe, being recreated. This may take a while because he is working with some big clients and just generally busy.
