### ISSUE TITLE
Doesn't Compile

### ISSUE THREAD

**Issue by KaspianDev** [LagBug/XProtect#3]
This project does not seem to compile. I've tried maven, gradle, javac neither of which worked.

**Comment by iiAhmedYT** [comment]
can confirm, looks like the link to the source code in the SpigotMC profile is false which means the author has his project with no license and he's not following the SpigotMC rules at the same time. beautiful.

**Comment by LagBug** [comment]
Sorry, the project's source code is currently private and will remain so in the near future. I've changed the SpigotMC source code label in the plugin's page.
