### ISSUE TITLE
Why must paying to hell?

### ISSUE THREAD

**Issue by Justman100** [LagBug/XProtect#9]
If this Plugin opensource, why [one must pay](https://www.spigotmc.org/resources/xprotect-the-best-protection-plugin-stop-bots-attacks-vpns-mysql-1-8-1-19.67863) for this?

**Comment by Justman100** [comment]
@LagBug

**Comment by Justman100** [comment]
@LagBug

**Comment by LagBug** [comment]
Hello, the plugin is made open source 1) so that even if someone can't pay, they can still compile the sourcecode and use it, and 2) to allow contributions. Yet, it's still with a price on SpigotMC as a means of support, and because basically I'm the only one contributing.

**Comment by Justman100** [comment]
> Hello, the plugin is made open source 1) so that even if someone can't pay, they can still compile the sourcecode and use it, and 2) to allow contributions. Yet, it's still with a price on SpigotMC as a means of support, and because basically I'm the only one contributing.

Great, so the money is out the window 😒
